### ISSUE TITLE
plexus-utils optional plexus-xml is a problem!!!

### ISSUE THREAD

**Issue by hazendaz** [codehaus-plexus/plexus-utils#256]
Due pulling plexus-xml out to be optional, repos that rely on that which need to upgrade have to have plexus-xml now.  We cannot make that simply provided as 4.0 won't even exist prior too and recent releases of maven required plexus-utils in compile scope.

...

Some dependencies of Maven Plugins are expected to be in provided scope.
Please make sure that dependencies listed below declared in POM
have set '<scope>provided</scope>' as well.

The following dependencies are in wrong scope:
 * org.apache.maven:maven-xml-impl:jar:4.0.0-alpha-5:compile
 * org.apache.maven:maven-api-xml:jar:4.0.0-alpha-5:compile
 * org.apache.maven:maven-api-meta:jar:4.0.0-alpha-5:compile

see https://github.com/codehaus-plexus/plexus-xml/issues/16

**Comment by gnodet** [comment]
I'm not sure to understand where the actual problem is.  I see two things in your issue: the fact that the xml has been extracted, and that's a real compatibility and won't be fixed (hence the major version).  To fix this, you need to add a dependency on `plexus-xml`.  For the warnings, they will be hopefully be fixed in the maven checks somehow, but there's no actionable thing to do (or planned) in `plexus-utils` for that.

**Comment by gnodet** [comment]
The warnings are actually provided at build time by the maven-plugin-plugin.  It will have to be enhanced.

**Comment by gnodet** [comment]
This cannot be fixed in `plexus-xml` or `plexus-utils`.  I've raised https://issues.apache.org/jira/browse/MPLUGIN-473 to fix the problem.
